/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TwentyFace */

#ifndef _Included_F5C
#define _Included_F5C
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     TwentyFace
 * Method:    init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT int JNICALL Java_F5C_init
  (JNIEnv *, jclass, jstring);


#ifdef __cplusplus
}
#endif
#endif